# Generated by Django 5.0.6 on 2024-12-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mehanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default='+998')),
                ('telegram_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
            ],
        ),
    ]
