# Generated by Django 5.0.6 on 2024-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('photo', models.ImageField(upload_to='usta_photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Mehanic',
        ),
    ]
